### ISSUE TITLE
Does Not Work with Namespaced Controllers as a routes file would

### ISSUE THREAD

**Issue by matalina** [guiwoda/route-binder#5]
I don't know if this was intentional or not, but I thought I would let you know that I had to write the full namespace in my uses argument for controlloers  (with default Laravel 5 install)

**Comment by guiwoda** [comment]
Hi @matalina!
Indeed it doesn't. As your route bindings will be objects (instead of plain php files), and you'll probably have many of them for your different routing concerns, I don't see it necessary to resolve the FQCN of your controllers for you.

I usually have only one controller reference per RouteBinder class, and refer to it as follows:

``` php
namespace App\Http\Routes;

use App\Http\Controllers\FooController;
use Illuminate\Contracts\Routing\Registrar;
use LaravelBA\RouteBinder\RouteBinder;

class FooRouteBinder implements RouteBinder
{
    public function bind(Registrar $router)
    {
        $router->get('foo', FooController::class . '@index');
    }
}
```

Hope this helps!

**Comment by GrahamCampbell** [comment]
That way you're still writing the FQCN out, just in a different place...

**Comment by guiwoda** [comment]
@GrahamCampbell yes, I do write the full FQCN!
Didn't mean otherwise, sorry if it's confusing!

**Comment by matalina** [comment]
Yes that helps.  I always just use the sting not the class method inherent in objects.  That makes more sense .  Thank you.

**Comment by guiwoda** [comment]
Using the class constant requires php >5.5, keep that in mind when deploying!
