### ISSUE TITLE
Suggestion:  Changelog

### ISSUE THREAD

**Issue by matalina** [guiwoda/route-binder#6]
I just updated and everything broke.

A note when you make big changes like changing your interface and renaming your config file would be helpful.  Took me forever to find the problem.

**Comment by guiwoda** [comment]
Hi @matalina! Thank you for your suggestion.

I decided to upgrade the interface and bumped a major version because I knew this would break compatibility. I'm fully open for a PR of a changelog, to ease migration between major versions, although this library is so small, I believe it doesn't require a lot of effort to understand.

Usually major version updates shouldn't be done without checking what changed, and I understand your frustration on finding changes weren't documented. But, being honest, was it that hard to find? I'd approximate your "forever" to "less than an hour", tops. But, again, I do appreciate your suggestion, and you're welcome to contribute a changelog to avoid this issue on other projects as well!
